---
os: linux
dist: bionic
language: python
services: docker

env:
  global:
    - COLLECTION_NAMESPACE: anton-sidelnikov
    - COLLECTION_NAME: csm-ansible-collection
  matrix:
    - DISTRO: ubuntu-18.04
    - DISTRO: debian-buster

install:
  # Install test dependencies.
  - pip install ansible molecule yamllint ansible-lint docker

before_script:
  # Move the collection into the required path.
  - cd ../
  - mkdir -p ansible_collections/$COLLECTION_NAMESPACE
  - mv ansible-collection-$COLLECTION_NAME ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME
  - cd ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

script:
  # Run test-manifests scenario.
  - molecule test

deploy:
  provider: script
  script: ansible-playbook -i 'localhost,' scripts/deploy.yml -e "tag=$TRAVIS_TAG"
  'on':
    tags: true
    condition: $MOLECULE_DISTRO = default